import { Droplets, Zap, Dam } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import FactBox from '@/components/shared/FactBox';

export default function Hydropower() {
  return (
    <div className="container py-12 space-y-16">
      <section className="text-center space-y-4">
        <Droplets className="h-16 w-16 text-eco-blue mx-auto" />
        <h1 className="text-4xl md:text-5xl font-bold">Hydropower</h1>
        <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
          Harnessing the power of flowing water to generate clean, reliable electricity
        </p>
      </section>

      <section className="space-y-6">
        <h2 className="text-3xl font-bold">What is Hydropower?</h2>
        <Card>
          <CardContent className="pt-6 space-y-4">
            <p className="text-lg leading-relaxed">
              Hydropower, or hydroelectric power, is electricity generated by harnessing the energy of moving water. 
              It's one of the oldest and most widely used forms of renewable energy, providing about 16% of global 
              electricity generation. Hydropower plants convert the kinetic energy of flowing or falling water into 
              mechanical energy via turbines, which then drive generators to produce electricity.
            </p>
            <p className="text-lg leading-relaxed">
              The fundamental principle is simple: water stored at a height has gravitational potential energy. When 
              released, this potential energy converts to kinetic energy as the water flows downward. This moving water 
              spins turbine blades, which rotate a generator to produce electricity. The greater the height (head) and 
              volume of water, the more power can be generated.
            </p>
          </CardContent>
        </Card>
      </section>

      <section className="space-y-6">
        <h2 className="text-3xl font-bold">How Hydropower Works</h2>
        <Card>
          <CardContent className="pt-6 space-y-6">
            <img
              src="/assets/generated/hydropower-diagram.dim_800x600.png"
              alt="Diagram showing hydropower dam with reservoir, penstock, turbine, generator, and power transmission"
              className="w-full rounded-lg"
            />
            <div className="grid md:grid-cols-2 gap-6">
              <div className="space-y-3">
                <h3 className="text-xl font-semibold text-eco-blue">The Generation Process</h3>
                <div className="p-4 bg-muted/50 rounded-lg space-y-2">
                  <p className="text-sm text-muted-foreground">
                    <strong>1. Water Storage:</strong> A dam creates a reservoir, storing water at an elevated height 
                    to build potential energy.
                  </p>
                  <p className="text-sm text-muted-foreground">
                    <strong>2. Controlled Release:</strong> Water is released through intake gates and flows down through 
                    large pipes called penstocks.
                  </p>
                  <p className="text-sm text-muted-foreground">
                    <strong>3. Turbine Rotation:</strong> The force of falling water strikes turbine blades, causing them 
                    to spin at high speed.
                  </p>
                  <p className="text-sm text-muted-foreground">
                    <strong>4. Electricity Generation:</strong> The spinning turbine drives a generator, converting 
                    mechanical energy into electrical energy.
                  </p>
                  <p className="text-sm text-muted-foreground">
                    <strong>5. Transmission:</strong> Electricity is sent to the power grid through transformers and 
                    transmission lines.
                  </p>
                </div>
              </div>
              <div className="space-y-3">
                <h3 className="text-xl font-semibold text-eco-green">Key Components</h3>
                <div className="space-y-2">
                  <div className="p-3 bg-muted/50 rounded-lg">
                    <h4 className="font-semibold text-sm">Dam & Reservoir</h4>
                    <p className="text-xs text-muted-foreground">Stores water and creates the height difference (head) needed for power generation</p>
                  </div>
                  <div className="p-3 bg-muted/50 rounded-lg">
                    <h4 className="font-semibold text-sm">Penstock</h4>
                    <p className="text-xs text-muted-foreground">Large pipe that channels water from reservoir to turbine</p>
                  </div>
                  <div className="p-3 bg-muted/50 rounded-lg">
                    <h4 className="font-semibold text-sm">Turbine</h4>
                    <p className="text-xs text-muted-foreground">Converts water's kinetic energy into rotational mechanical energy</p>
                  </div>
                  <div className="p-3 bg-muted/50 rounded-lg">
                    <h4 className="font-semibold text-sm">Generator</h4>
                    <p className="text-xs text-muted-foreground">Converts mechanical rotation into electrical energy</p>
                  </div>
                  <div className="p-3 bg-muted/50 rounded-lg">
                    <h4 className="font-semibold text-sm">Transformer</h4>
                    <p className="text-xs text-muted-foreground">Steps up voltage for efficient long-distance transmission</p>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </section>

      <FactBox
        fact="Hydropower is incredibly efficient—modern turbines can convert over 90% of available energy into electricity, compared to 30-40% for fossil fuel plants!"
        icon={<Zap className="h-6 w-6" />}
      />

      <section className="space-y-6">
        <h2 className="text-3xl font-bold">Types of Hydropower Plants</h2>
        <div className="grid md:grid-cols-2 gap-6">
          <Card className="border-eco-blue/50">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Dam className="h-6 w-6 text-eco-blue" />
                Impoundment (Dam-Based)
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <p className="text-muted-foreground">
                The most common type, using a dam to store water in a reservoir. Water is released through turbines as 
                needed to generate electricity. Provides reliable baseload power and can quickly adjust output to meet 
                demand.
              </p>
              <div className="space-y-2">
                <h4 className="font-semibold text-sm">Advantages:</h4>
                <ul className="text-sm text-muted-foreground space-y-1">
                  <li>• Large-scale power generation (100s-1000s of MW)</li>
                  <li>• Provides flood control and water storage</li>
                  <li>• Creates recreational opportunities (boating, fishing)</li>
                  <li>• Can store energy by pumping water back up (pumped storage)</li>
                </ul>
              </div>
              <div className="space-y-2">
                <h4 className="font-semibold text-sm">Challenges:</h4>
                <ul className="text-sm text-muted-foreground space-y-1">
                  <li>• High initial construction costs</li>
                  <li>• Disrupts river ecosystems and fish migration</li>
                  <li>• Displaces communities and floods land</li>
                  <li>• Reservoir evaporation in hot climates</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card className="border-eco-green/50">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Droplets className="h-6 w-6 text-eco-green" />
                Run-of-River
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <p className="text-muted-foreground">
                Uses the natural flow and elevation drop of a river without a large reservoir. Water is diverted through 
                a canal or penstock to turbines, then returned to the river. Minimal water storage means output varies 
                with river flow.
              </p>
              <div className="space-y-2">
                <h4 className="font-semibold text-sm">Advantages:</h4>
                <ul className="text-sm text-muted-foreground space-y-1">
                  <li>• Minimal environmental impact on river ecosystems</li>
                  <li>• Lower construction costs and faster to build</li>
                  <li>• No large-scale flooding or displacement</li>
                  <li>• Maintains natural river flow patterns</li>
                </ul>
              </div>
              <div className="space-y-2">
                <h4 className="font-semibold text-sm">Challenges:</h4>
                <ul className="text-sm text-muted-foreground space-y-1">
                  <li>• Power output varies with seasonal river flow</li>
                  <li>• Cannot store water for peak demand periods</li>
                  <li>• Typically smaller capacity (1-50 MW)</li>
                  <li>• Vulnerable to droughts</li>
                </ul>
              </div>
            </CardContent>
          </Card>
        </div>
      </section>

      <section className="space-y-6">
        <h2 className="text-3xl font-bold">Pumped Storage Hydropower</h2>
        <Card className="bg-gradient-to-br from-eco-blue/10 to-eco-green/10">
          <CardContent className="pt-6 space-y-4">
            <p className="text-lg leading-relaxed">
              Pumped storage is a special type of hydropower that acts like a giant battery. During periods of low 
              electricity demand (typically at night), excess power from the grid is used to pump water from a lower 
              reservoir to an upper reservoir. During peak demand, water is released back down through turbines to 
              generate electricity.
            </p>
            <div className="grid md:grid-cols-3 gap-4">
              <div className="text-center p-4 bg-background/50 rounded-lg">
                <div className="text-3xl mb-2">⬆️</div>
                <p className="font-semibold mb-1">Charging</p>
                <p className="text-sm text-muted-foreground">Pump water up during low demand</p>
              </div>
              <div className="text-center p-4 bg-background/50 rounded-lg">
                <div className="text-3xl mb-2">💧</div>
                <p className="font-semibold mb-1">Storage</p>
                <p className="text-sm text-muted-foreground">Water stored as potential energy</p>
              </div>
              <div className="text-center p-4 bg-background/50 rounded-lg">
                <div className="text-3xl mb-2">⚡</div>
                <p className="font-semibold mb-1">Discharging</p>
                <p className="text-sm text-muted-foreground">Generate power during peak demand</p>
              </div>
            </div>
            <p className="text-muted-foreground">
              Pumped storage accounts for over 95% of global energy storage capacity and is crucial for grid stability, 
              especially as more variable renewable sources like wind and solar are added to the grid.
            </p>
          </CardContent>
        </Card>
      </section>

      <FactBox
        fact="The Three Gorges Dam in China is the world's largest power station of any kind, with a capacity of 22,500 MW—enough to power over 15 million homes!"
        icon={<Dam className="h-6 w-6" />}
      />

      <section className="space-y-6">
        <h2 className="text-3xl font-bold">Global Hydropower</h2>
        <Card>
          <CardContent className="pt-6">
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-[200px]">Country</TableHead>
                    <TableHead>Installed Capacity (GW)</TableHead>
                    <TableHead>% of Electricity</TableHead>
                    <TableHead>Notable Features</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell className="font-medium">China</TableCell>
                    <TableCell className="text-eco-green">370 GW</TableCell>
                    <TableCell>17%</TableCell>
                    <TableCell>World's largest capacity, Three Gorges Dam</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Brazil</TableCell>
                    <TableCell className="text-eco-green">109 GW</TableCell>
                    <TableCell>63%</TableCell>
                    <TableCell>Itaipu Dam, heavy reliance on hydro</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Canada</TableCell>
                    <TableCell className="text-eco-green">82 GW</TableCell>
                    <TableCell>59%</TableCell>
                    <TableCell>Abundant water resources, exports power</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">United States</TableCell>
                    <TableCell className="text-eco-blue">103 GW</TableCell>
                    <TableCell>7%</TableCell>
                    <TableCell>Hoover Dam, Grand Coulee Dam</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Norway</TableCell>
                    <TableCell className="text-eco-blue">33 GW</TableCell>
                    <TableCell>92%</TableCell>
                    <TableCell>Highest percentage in developed world</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">India</TableCell>
                    <TableCell className="text-eco-blue">51 GW</TableCell>
                    <TableCell>10%</TableCell>
                    <TableCell>Rapidly expanding capacity</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      </section>

      <section className="space-y-6">
        <h2 className="text-3xl font-bold">Benefits and Challenges</h2>
        <div className="grid md:grid-cols-2 gap-6">
          <Card className="border-eco-green/50">
            <CardHeader>
              <CardTitle className="text-eco-green">Benefits</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 text-muted-foreground">
                <li>• Renewable and produces no direct emissions</li>
                <li>• Highly efficient (85-90% conversion efficiency)</li>
                <li>• Provides reliable baseload power</li>
                <li>• Can quickly adjust output to meet demand</li>
                <li>• Long lifespan (50-100+ years)</li>
                <li>• Low operating costs after construction</li>
                <li>• Provides flood control and water storage</li>
                <li>• Creates recreational opportunities</li>
                <li>• Pumped storage enables large-scale energy storage</li>
              </ul>
            </CardContent>
          </Card>

          <Card className="border-earth-brown/50">
            <CardHeader>
              <CardTitle className="text-earth-brown">Challenges</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2 text-muted-foreground">
                <li>• High upfront construction costs</li>
                <li>• Disrupts river ecosystems and fish migration</li>
                <li>• Can displace communities and flood land</li>
                <li>• Alters downstream water flow and sediment transport</li>
                <li>• Reservoir methane emissions in tropical regions</li>
                <li>• Vulnerable to droughts and climate change</li>
                <li>• Limited suitable sites remaining in developed countries</li>
                <li>• Long construction timelines (5-10+ years)</li>
                <li>• Potential dam failure risks</li>
              </ul>
            </CardContent>
          </Card>
        </div>
      </section>
    </div>
  );
}
